[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
board_build.flash_mode = dout
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
monitor_speed = 115200

; Max range & performance settings
board_build.extra_flags = 
    -DCONFIG_PHY_TX_POWER_MAX=20
    -DCONFIG_ESP32_PHY_MAX_TX_POWER=20
    -DCONFIG_ESP32_PHY_CALIBRATION_AND_DATA_STORAGE=n
    -DCONFIG_ESP32_PHY_DISABLE_LONG_RANGE=n
    -DCONFIG_ESP32_WIFI_TX_POWER=20
    -DCONFIG_ESP_WIFI_BEACON_INTERVAL=200
    -DCONFIG_ESP_WIFI_STATIC_TX_BUFFER_NUM=16
    -DCONFIG_ESP_WIFI_DYNAMIC_TX_BUFFER_NUM=64
    -DCONFIG_ESP_WIFI_RX_BA_WIN=6
    -DCONFIG_ESP_WIFI_AMPDU_TX_ENABLED=y
    -DCONFIG_ESP_WIFI_AMPDU_RX_ENABLED=y
    -DCONFIG_ESP_WIFI_NVS_ENABLED=n

build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
board_build.partitions = huge_app.csv
